app:
  couchbase:
    connection-string: couchbase://127.0.0.1
    user-name: Administrator
    password: 899091
    bucket-todo: todo-app
    bucket-user: user

spring:
  data:
    couchbase:
      auto-index: true